routes/web.php
<?php

//Dashboards
use App\Http\Controllers\Configuration\Dashboard\DashboardController as ConfigurationDashboardController;
use App\Http\Controllers\Inventory\Dashboard\DashboardController as InventoryDashboardController;
use App\Http\Controllers\Outbound\Dashboard\DashboardController as OutboundDashboardController;
use App\Http\Controllers\Inbound\Dashboard\DashboardController as InboundDashboardController;
//Configuration
use App\Http\Controllers\Configuration\Devices\DeviceController;
use App\Http\Controllers\Configuration\Devices\DeviceTypeController;
use App\Http\Controllers\Configuration\Hardware\PrinterController;
use App\Http\Controllers\Configuration\Hardware\PrinterTypeController;
use App\Http\Controllers\Configuration\Inbound\InboundConfigController;
use App\Http\Controllers\Configuration\Inbound\StorageRuleController;
use App\Http\Controllers\Configuration\Locations\LocationTypeController;
use App\Http\Controllers\Configuration\MobileConfiguration\MobileMenuController;
use App\Http\Controllers\Configuration\Outbound\PickTypeController;
use App\Http\Controllers\Configuration\Products\ProductTypeController;
use App\Http\Controllers\Configuration\Products\UOMController;
use App\Http\Controllers\Configuration\Uploads\ConfigUploadController;
use App\Http\Controllers\Configuration\Work\WorkTypeController;
use App\Http\Controllers\Configuration\Zones\CountZoneController;
use App\Http\Controllers\Configuration\Zones\PickZoneController;
use App\Http\Controllers\Configuration\Zones\StorageZoneController;
//Inbound
use App\Http\Controllers\Inbound\Deliveries\DeliveryReceiptController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryStagingController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryDetailController;
use App\Http\Controllers\Inbound\CheckInController;
//Outbound
use App\Http\Controllers\Outbound\Constraints\ConstraintController;
//Inventory
use App\Http\Controllers\Inventory\Products\ProductDetailController;
use App\Http\Controllers\Inventory\Products\ProductController;
use App\Http\Controllers\Inventory\Holds\HoldController;
use App\Http\Controllers\Inventory\InventoryStatus\InventoryStatusController;
//Locations
use App\Http\Controllers\Locations\LocationController;
use App\Http\Controllers\Doors\DoorController;
use App\Http\Controllers\Inventory\Holds\HoldTypeController;
use App\Http\Controllers\StagingLanes\InboundStagingLaneController;
//Work
use App\Http\Controllers\Work\WorkController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    //home
    Route::view('/dashboard', 'dashboard')->name('dashboard');

    //locations
    Route::resource('location', LocationController::class);

    //work
    Route::resource('work', WorkController::class);

    //inbound
    Route::group(['prefix' => 'inbound', 'as' => 'inbound.'], function () {

        Route::get('dashboard', InboundDashboardController::class)->name('dashboard');
        Route::get('checkIn/{delivery}', [CheckInController::class, 'index'])->name('checkIn');
        Route::post('checkInConfirm/{delivery}', [CheckInController::class, 'store'])->name('checkInConfirm');

        Route::resource('deliveries', DeliveryController::class);
        Route::resource('deliveryDetails', DeliveryDetailController::class);
        Route::resource('stagingLanes', DeliveryStagingController::class);
        Route::resource('receipt', DeliveryReceiptController::class);
    });

    //outbound
    Route::group(['prefix' => 'outbound', 'as' => 'outbound.'], function () {
        //Route::get('dashboard', OutboundDashboardController::class)->name('dashboard');
        Route::resource('constraints', ConstraintController::class);
    });

    //inventory
    Route::group(['prefix' => 'inventory', 'as' => 'inventory.'], function () {

        Route::get('dashboard', InventoryDashboardController::class)->name('dashboard');
        Route::resource('product', ProductController::class);
        Route::get('productDetails/{product}', [ProductDetailController::class, 'ajax']);
        Route::resource('productDetail', ProductDetailController::class);
        Route::resource('inventoryStatus', InventoryStatusController::class);
        Route::resource('holdTypes', HoldTypeController::class);
        Route::resource('holds', HoldController::class);
    });

    //Doors
    Route::resource('doors', DoorController::class);


    //Staging Lanes
    Route::resource('stagingLanes', InboundStagingLaneController::class);


    //Configuration
    Route::group(['prefix' => 'Configuration', 'as' => 'config.'], function () {
        Route::get('dashboard', ConfigurationDashboardController::class)->name('dashboard');

        //Mobile Devices
        Route::post('mobileConfigSort', [MobileMenuController::class, 'updateSortOrder'])->name('mobileConfigSort');       
        Route::resource('mobileConfig', MobileMenuController::class);

        //Products
        Route::resource('productTypes', ProductTypeController::class);
        Route::resource('UOMS', UOMController::class);

        //Locations 
        Route::get('locationTypes/{location_type}', [LocationTypeController::class, 'showLocations'])->name('showLocations');
        Route::resource('locationTypes', LocationTypeController::class);

        //Zones 
        Route::resource('countZones', CountZoneController::class);
        Route::resource('pickZones', PickZoneController::class);
        Route::resource('storageZones', StorageZoneController::class);

        //Devices
        Route::resource('deviceTypes', DeviceTypeController::class);
        Route::resource('devices', DeviceController::class);

        //Printers
        Route::resource('printers', PrinterController::class);
        Route::resource('printerTypes', PrinterTypeController::class);

        //Outbound
        Route::resource('pickTypes', PickTypeController::class);

        //Inbound
        Route::resource('inboundConfig', InboundConfigController::class);
        Route::resource('storageRules', StorageRuleController::class);

        //Uploads
        Route::resource('configupload', ConfigUploadController::class);

        //Work
        Route::resource('workTypes', WorkTypeController::class);
    });
});

app/Models/Inbound/InboundConfig.php
<?php

namespace App\Models\Inbound;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InboundConfig extends Model
{
    use HasFactory;

    protected $fillable =[
        'truck_required',
        'truck_required_by_supplier',
        'short_receive',
        'shorts_by_supplier',
        'over_receive',
        'over_receipt_by_supplier',
        'mobile_can_close',
        'mobile_can_dispatch'
    ];
}

app/Http/Controllers/Configuration/Inbound/DeliveryTypeController.php
<?php

namespace App\Http\Controllers\Configuration\Inbound;

use App\Http\Controllers\Controller;
use App\Models\ReceiptType;
use Illuminate\Http\Request;

class DeliveryTypeController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ReceiptType  $receiptType
     * @return \Illuminate\Http\Response
     */
    public function show(ReceiptType $receiptType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ReceiptType  $receiptType
     * @return \Illuminate\Http\Response
     */
    public function edit(ReceiptType $receiptType)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ReceiptType  $receiptType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ReceiptType $receiptType)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ReceiptType  $receiptType
     * @return \Illuminate\Http\Response
     */
    public function destroy(ReceiptType $receiptType)
    {
        //
    }
}

app/Http/Controllers/Configuration/Inbound/InboundConfigController.php
<?php

namespace App\Http\Controllers\Configuration\Inbound;

use App\Http\Controllers\Controller;
use App\Models\Inbound\InboundConfig;
use Illuminate\Http\Request;

class InboundConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
     
        return view('configuration.inbound.inbound-rules', [
            'rules' => InboundConfig::first()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Inbound\InboundConfig  $inboundConfig
     * @return \Illuminate\Http\Response
     */
    public function show(InboundConfig $inboundConfig)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Inbound\InboundConfig  $inboundConfig
     * @return \Illuminate\Http\Response
     */
    public function edit(InboundConfig $inboundConfig)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Inbound\InboundConfig  $inboundConfig
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, InboundConfig $inboundConfig)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Inbound\InboundConfig  $inboundConfig
     * @return \Illuminate\Http\Response
     */
    public function destroy(InboundConfig $inboundConfig)
    {
        //
    }
}

app/Http/Controllers/Configuration/Inbound/StorageRuleController.php
<?php

namespace App\Http\Controllers\Configuration\Inbound;

use App\Http\Controllers\Controller;
use App\Models\Inbound\StorageRule;
use App\Models\Products\ProductType;
use App\Models\Uom;
use App\Models\Zones\StorageZone;
use App\Services\StorageRules\StorageRuleDetailService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StorageRuleController extends Controller
{

    private $ruleDetailService;
    

    public function __construct()
    {
        $this->ruleDetailService = new StorageRuleDetailService;
    }


    public function index()
    {
        $storageRules = StorageRule::all();
        return view('configuration.inbound.storage-rules', [
            'storageRules' => $storageRules
        ]);
    }


    public function create()
    {
        return view('configuration.inbound.create-storage-rule', [
            'storageZones' => StorageZone::all(),
            'productTypes' => ProductType::all(),
            'uoms' => Uom::all()
        ]);
    }


    public function store(Request $request)
    {
      
        if(!$request->has('storageZones')){
            session()->flash('error', ' At least one Storage Zone is required');
            return back()->withInput();
        };

        DB::transaction(function () use ($request) {
            $storageRule = StorageRule::create([
                'name' => $request->name,
                'description' => $request->description,
                'sequence' => $request->sequence
            ]);

            $this->ruleDetailService->createStorageRuleDetail($request, $storageRule->id);
        });


        return redirect()->route('config.storageRules.index');
    }

 
    public function show(StorageRule $storageRule)
    {
        //
    }


    public function edit(StorageRule $storageRule)
    {
        //
    }


    public function update(Request $request, StorageRule $storageRule)
    {
        //
    }


    public function destroy(StorageRule $storageRule)
    {
        //
    }
}

app/Http/Controllers/Configuration/Inbound/StorageRuleDetailController.php
<?php

namespace app\Http\Controllers;

use App\Models\Inbound\StorageRuleDetail;
use Illuminate\Http\Request;

class StorageRuleDetailController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\StorageRuleDetail  $storageRuleDetail
     * @return \Illuminate\Http\Response
     */
    public function show(StorageRuleDetail $storageRuleDetail)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\StorageRuleDetail  $storageRuleDetail
     * @return \Illuminate\Http\Response
     */
    public function edit(StorageRuleDetail $storageRuleDetail)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\StorageRuleDetail  $storageRuleDetail
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, StorageRuleDetail $storageRuleDetail)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\StorageRuleDetail  $storageRuleDetail
     * @return \Illuminate\Http\Response
     */
    public function destroy(StorageRuleDetail $storageRuleDetail)
    {
        //
    }
}

app/Http/Controllers/Inbound/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Inbound\Dashboard;

use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __invoke()
    {
        return view('inbound.dashboard');
    }
}

app/Http/Controllers/Inbound/Deliveries/DeliveryController.php
<?php

namespace App\Http\Controllers\Inbound\Deliveries;

use App\Http\Controllers\Controller;
use App\Http\Requests\Inbound\CreateInboundDeliveryRequest;
use App\Models\Delivery;

use App\Services\Inbound\InboundDeliveryService;
use Illuminate\Http\Request;

use App\Models\DeliveryDetail;
use App\Models\Inbound\InboundType;
use App\Models\Inbound\Supplier;
use App\Models\Product;

class DeliveryController extends Controller
{

    private $deliveryService;

    public function __construct()
    {
        $this->deliveryService = new InboundDeliveryService;
    }


    public function index()
    {
        return view('inbound.deliveries-table', [
            'deliveries' => Delivery::withCount('deliveryDetails')
                ->orderBy('due_date', 'ASC')->paginate(10),
        ]);
    }


    public function create()
    {
        $suppliers = Supplier::all();
        $inboundtypes = InboundType::all();

        return view('inbound.create-delivery', [
            'suppliers' => $suppliers,
            'inboundtypes' => $inboundtypes,
        ]);
    }


    public function store(CreateInboundDeliveryRequest $request)
    {

        $delivery = $this->deliveryService->storeInboundDelivery($request->validated());

        return view('inbound.delivery-details', [
            'delivery' => $delivery,
            'supplier' => Supplier::where('id', $delivery->supplier_id),
            'deliveryDetails' => DeliveryDetail::where('dellivery_id', $delivery->id),
            'products' => Product::all()
        ]);
    }


    public function show(Delivery $delivery)
    {

        return view('inbound.delivery-details', [
            'delivery' => $delivery,
            'supplier' => Supplier::where('id', $delivery->supplier_id),
            'deliveryDetails' => DeliveryDetail::where('delivery_id', $delivery->id),
            'products' => Product::all()
        ]);
    }


    public function update(Request $request, Delivery $delivery)
    {
        //
    }


    public function destroy(Delivery $delivery)
    {
        $delivery->delete();

        return redirect()->route('inbound.deliveries.index')->with('success', ' Delivery deleted successfully!');
    }
}

resources/views/inbound/dashboard.blade.php
<x-wms-layout>
    @section('content')
    <div class="h-auto">
            @include('inbound.navbar')
            <div class="flex justify-between justify-items-center h-14 shadow-lg">
                <h1 class="flex font-semibold text-2xl px-4 items-center py-2">{{__('Inbound Dashboard') }}</h1>
            </div>
            <div>Inbound Dashboard Things..</div>
        </div>
    @endsection
</x-wms-layout>

resources/views/inbound/delivery-details.blade.php
<x-wms-layout>
    @section('content')
        <div class="h-auto" x-data="{ showModal: false }">
            @include('inbound.navbar')
            @include('flash-message')
            <div class="flex justify-items-center justify-start border-b-2 border-gray-500 h-14">
                @if ($delivery->checked_in_flg == true)
                    <h1 class="flex font-bold text-xl px-4 items-center py-2">
                        {{ __('Delivery: ') }}{{ $delivery->delivery_ref }}{{ ' - ' }}<span
                            class="text-green-500 pl-2">{{ __('Checked In') }}</span></h1>
                    @if ($delivery->lane == null)
                        <form action="{{ route('inbound.stagingLanes.show', $delivery) }}" method="GET">
                            @csrf
                            <button type="submit"
                                class="bg-blue-600 hover:bg-blue-700 focus:outline-none rounded mr-2 px-2 text-center h-8 mt-2 font-semibold text-white inline">{{ __('Start Receiving') }}</button>
                            <input hidden value="{{ $delivery }}" name="delivery">
                            <a href="{{ route('inbound.deliveries.index') }}"><button @submit.prevent
                                    class="bg-red-500 hover:bg-red-700 focus:outline-none rounded mr-2 px-4 h-8 mt-2 text-center font-semibold text-white">{{ __('Back') }}
                                </button></a>
                            </a>
                        </form>
                    @else
                        <form action="{{ route('inbound.receipt.show', $delivery) }}" method="GET">
                            @csrf
                            <button type="submit"
                                class="bg-blue-600 hover:bg-blue-700 focus:outline-none rounded mr-2 py-2 px-2 text-center mt-2 font-semibold text-white inline">{{ __('Start Receiving') }}</button>
                            <input hidden value="{{ $delivery }}" name="delivery">
                            <a href="{{ route('inbound.deliveries.index') }}"
                                class="bg-red-500 hover:bg-red-700 focus:outline-none rounded mr-2 py-2 px-4 my-2 text-center font-semibold text-white">{{ __('Back') }}</a>
                            </a>
                        </form>
                    @endif
                @else
                    <h1 class="flex font-bold text-xl px-4 items-center py-2">
                        {{ __('Delivery: ') }}{{ $delivery->delivery_ref }}</h1>
                    <form action="{{ route('inbound.checkIn', $delivery) }}" method="GET">
                        @csrf
                        <button type="submit"
                            class="bg-blue-500 hover:bg-blue-700 focus:outline-none rounded mr-2 px-2 text-center h-8 mt-2 font-semibold text-white inline">{{ __('Check in') }}</button>
                        <input hidden value="{{ $delivery }}" name="delivery">
                    </form>
                    <form action="{{ route('inbound.deliveries.destroy', $delivery) }}" method='POST'>
                        @csrf
                        @method('DELETE')
                        <button type="submit"
                            class="bg-red-500 hover:bg-red-700 focus:outline-none rounded mr-2 px-2 text-center h-8 my-2 font-semibold text-white inline">{{ __('Cancel Delivery') }}</button>
                    </form>
                @endif
            </div>
            <div class="flex items-center h-full w-full">
                <div class="flex-grow h-full p-4 overflow-y-auto rounded-lg">
                    <label for="dueDate" class="font-semibold">{{ __('Due Date:') }}</label>
                    <br>
                    @if ($delivery->checked_in_flg == true)
                        <input type="date" name="dueDate" value={{ $delivery->due_date }} disabled
                            class="rounded-lg focus:outline-none focus:ring-0 focus:bg-gray-100">
                    @else
                        <input type="date" name="dueDate" value={{ $delivery->due_date }}
                            class="rounded-lg focus:outline-none focus:ring-0 focus:bg-gray-100">
                    @endif
                    @error('dueDate') <span class="error text-red-500">{{ $message }}</span>
                    @enderror
                    <h2 class="text-md py-2 pl-12 inline"><span
                            class="font-bold">{{ __('Supplier Name: ') }}</span>{{ $delivery->supplier->name }}
                    </h2>
                    <h2 class="text-md py-2 pl-12 inline"><span class="font-bold">
                            {{ __('Lines: ') }}</span>{{ count($delivery->deliveryDetails) }}</h2>
                    @if ($delivery->checked_in_flg == true)
                        <h2 class="text-md py-2 pl-12 inline"><span
                                class="font-bold">{{ __('Door: ') }}</span>{{ $delivery->door }}
                        </h2>
                    @endif
                    <div class="my-2">
                        @if ($delivery->checked_in_flg == false)
                            <x-buttons.primary class="mt-2 h-8">{{ __('Add Line') }}</x-buttons.primary>
                        @endif
                    </div>
                    <table class="w-full bg-white ">
                        <thead class="bg-gray-200 text-left">
                            <th class="py-2 pl-2">{{ __('Item') }}</th>
                            <th class="py-2 pl-2">{{ __('Batch') }}</th>
                            <th class="py-2 pl-2">{{ __('Expected Qty') }}</th>
                            <th class="py-2 pl-2">{{ __('Received Qty') }}</th>
                            <th class="py-2 pl-2">{{ __('Short Qty') }}</th>
                            <th class="py-2 pl-2">{{ __('Uom') }}</th>
                        </thead>
                        <tbody class="bg-grey-light">
                            @forelse ($delivery->deliveryDetails as $deliveryDetail)
                                <tr class="hover:bg-gray-100 border-b-2">
                                    <td class="pl-2">{{ $deliveryDetail->product }}</td>
                                    <td class="pl-2">{{ $deliveryDetail->batch ?: 'n\\a' }}</td>
                                    <td class="pl-2">{{ $deliveryDetail->expected_qty }}</td>
                                    <td class="pl-2">{{ $deliveryDetail->received_qty }}</td>
                                    <td class="pl-2">{{ $deliveryDetail->short_qty }}</td>
                                    <td class="pl-2">{{ $deliveryDetail->uom }}</td>
                                @empty
                                    <td class="pl-2 text-red-500 italic">
                                        {{ __('This delivery has no pre-advised lines.') }}</td>
                                </tr>
                        </tbody>
                        @endforelse
                    </table>
                    @if ($delivery->checked_in_flg == false)
                        <!-- add delivery line Modal-->
                        <form method="POST" action="{{ route('inbound.deliveryDetails.store') }}">
                            @csrf
                            <x-modal>
                                <x-slot name="title" class="mb-2">
                                    {{ __('Add Line To Delivery: ') }}{{ $delivery->delivery_ref }}
                                </x-slot>
                                <input type="text" name="delivery_id" value="{{ $delivery->id }}" hidden />
                                <x-modal.input.dropdown label="{{ __('Product:') }}" name="product_id" required>
                                    <option value=""></option>
                                    @forelse ($products as $product)
                                        <option value="{{ $product->id }}">{{ $product->product }} -
                                            {{ $product->description }}
                                        </option>
                                    @empty
                                        <option value="">{{ __('No Products Found.') }}</option>
                                    @endforelse
                                </x-modal.input.dropdown>
                                <br />
                                <x-modal.input.dropdown label="{{ __('Uom:') }}" name="uom_id" class="bg-gray-200"
                                    disabled required>
                                    <option value=""></option>
                                </x-modal.input.dropdown>
                                <br />
                                <label class="mx-4 font-semibold">{{ __('Quantity:') }}</label>
                                <input
                                    class="mx-4 rounded-lg focus:outline-none focus:ring-0 focus:bg-gray-100 bg-gray-200 border-gray-400 "
                                    disabled type="number" min="1" name="qty" id="qty" placeholder="1" required />
                                <br>
                                <x-modal.input.textarea name="batch" placeholder='Batch...' />
                                <x-modal.input.textarea name="cust_batch" placeholder='Supplier Batch...' />
                            </x-modal>
                        </form>
                    @endif
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function() {
                $("select[name='product_id']").change(function() {

                        $("select[name='uom_id']").empty();

                        $('select[name="uom_id"]').append('<option value=""' + '</option>');

                        var productID = $(this).val();

                        if (productID) {

                            $.ajax({
                                type: "GET",
                                url: '{{ url('/') }}/inventory/productDetails/' + productID,

                                success: function(data) {
                                    console.log(data);
                                    $('select[name="uom_id"]').prop("disabled", false);
                                    $('select[name="uom_id"]').removeClass('bg-gray-200');

                                    $.each(data, function(key, value) {
                                        $('select[name="uom_id"]').append('<option value="' +
                                            value.uom_id + '">' + value.uom + ' - ' + value
                                            .description + '</option>');
                                    });
                                }
                            });
                        } else {
                            $('select[name="uom_id"]').prop("disabled", true);
                            $('select[name="uom_id"]').addClass('bg-gray-200');
                        };
                    }),
                    $("select[name='uom_id']").change(function() {

                        var uomID = $(this).val()

                        if (uomID) {

                            $("#qty").prop("disabled", false);
                            $("#qty").toggleClass('bg-gray-200 bg-gray-100');

                        } else {

                            $("#qty").prop("disabled", true);
                            $("#qty").toggleClass('bg-gray-200 bg-gray-100');
                        };

                    });
            });
        </script>
    @endsection
</x-wms-layout>

resources/views/inbound/edit-delivery.blade.php
<x-wms-layout>
    @section('content')
        <div class="flex-1">
            @include('inbound.navbar')
            @include('flash-message')
            @livewire('create-delivery')
        </div>
        @endsection
</x-wms-layout>

resources/views/inbound/navbar.blade.php
<div class="flex sticky top-16 h-14 justify-items-start gap-4 text-gray-800 pl-2 font-semibold bg-white border-b-2 border-gray-500">
    <div class="flex items-center hover:text-blue-400"><a href="{{ route('doors.index') }}">{{ __('Doors') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="{{ route('stagingLanes.index') }}">{{ __('Staging Lanes') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="{{ route('inbound.deliveries.index') }}">{{ __('Deliveries') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="#">{{ __('Returns') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="#">{{ __('View Planner') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="#">{{ __('Suppliers') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="#">{{ __('Check-in') }}</a></div>
    <div class="flex items-center hover:text-blue-400"><a href="{{ route('work.index') }}">{{ __('Work') }}</a></div>
</div>