routes/web.php
<?php

//Dashboards
use App\Http\Controllers\Configuration\Dashboard\DashboardController as ConfigurationDashboardController;
use App\Http\Controllers\Inventory\Dashboard\DashboardController as InventoryDashboardController;
use App\Http\Controllers\Outbound\Dashboard\DashboardController as OutboundDashboardController;
use App\Http\Controllers\Inbound\Dashboard\DashboardController as InboundDashboardController;
//Configuration
use App\Http\Controllers\Configuration\Devices\DeviceController;
use App\Http\Controllers\Configuration\Devices\DeviceTypeController;
use App\Http\Controllers\Configuration\Hardware\PrinterController;
use App\Http\Controllers\Configuration\Hardware\PrinterTypeController;
use App\Http\Controllers\Configuration\Inbound\InboundConfigController;
use App\Http\Controllers\Configuration\Inbound\StorageRuleController;
use App\Http\Controllers\Configuration\Locations\LocationTypeController;
use App\Http\Controllers\Configuration\MobileConfiguration\MobileMenuController;
use App\Http\Controllers\Configuration\Outbound\PickTypeController;
use App\Http\Controllers\Configuration\Products\ProductTypeController;
use App\Http\Controllers\Configuration\Products\UOMController;
use App\Http\Controllers\Configuration\Uploads\ConfigUploadController;
use App\Http\Controllers\Configuration\Work\WorkTypeController;
use App\Http\Controllers\Configuration\Zones\CountZoneController;
use App\Http\Controllers\Configuration\Zones\PickZoneController;
use App\Http\Controllers\Configuration\Zones\StorageZoneController;
//Inbound
use App\Http\Controllers\Inbound\Deliveries\DeliveryReceiptController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryStagingController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryController;
use App\Http\Controllers\Inbound\Deliveries\DeliveryDetailController;
use App\Http\Controllers\Inbound\CheckInController;
//Outbound
use App\Http\Controllers\Outbound\Constraints\ConstraintController;
//Inventory
use App\Http\Controllers\Inventory\Products\ProductDetailController;
use App\Http\Controllers\Inventory\Products\ProductController;
use App\Http\Controllers\Inventory\Holds\HoldController;
use App\Http\Controllers\Inventory\InventoryStatus\InventoryStatusController;
//Locations
use App\Http\Controllers\Locations\LocationController;
use App\Http\Controllers\Doors\DoorController;
use App\Http\Controllers\Inventory\Holds\HoldTypeController;
use App\Http\Controllers\StagingLanes\InboundStagingLaneController;
//Work
use App\Http\Controllers\Work\WorkController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    //home
    Route::view('/dashboard', 'dashboard')->name('dashboard');

    //locations
    Route::resource('location', LocationController::class);

    //work
    Route::resource('work', WorkController::class);

    //inbound
    Route::group(['prefix' => 'inbound', 'as' => 'inbound.'], function () {

        Route::get('dashboard', InboundDashboardController::class)->name('dashboard');
        Route::get('checkIn/{delivery}', [CheckInController::class, 'index'])->name('checkIn');
        Route::post('checkInConfirm/{delivery}', [CheckInController::class, 'store'])->name('checkInConfirm');

        Route::resource('deliveries', DeliveryController::class);
        Route::resource('deliveryDetails', DeliveryDetailController::class);
        Route::resource('stagingLanes', DeliveryStagingController::class);
        Route::resource('receipt', DeliveryReceiptController::class);
    });

    //outbound
    Route::group(['prefix' => 'outbound', 'as' => 'outbound.'], function () {
        //Route::get('dashboard', OutboundDashboardController::class)->name('dashboard');
        Route::resource('constraints', ConstraintController::class);
    });

    //inventory
    Route::group(['prefix' => 'inventory', 'as' => 'inventory.'], function () {

        Route::get('dashboard', InventoryDashboardController::class)->name('dashboard');
        Route::resource('product', ProductController::class);
        Route::get('productDetails/{product}', [ProductDetailController::class, 'ajax']);
        Route::resource('productDetail', ProductDetailController::class);
        Route::resource('inventoryStatus', InventoryStatusController::class);
        Route::resource('holdTypes', HoldTypeController::class);
        Route::resource('holds', HoldController::class);
    });

    //Doors
    Route::resource('doors', DoorController::class);


    //Staging Lanes
    Route::resource('stagingLanes', InboundStagingLaneController::class);


    //Configuration
    Route::group(['prefix' => 'Configuration', 'as' => 'config.'], function () {
        Route::get('dashboard', ConfigurationDashboardController::class)->name('dashboard');

        //Mobile Devices
        Route::post('mobileConfigSort', [MobileMenuController::class, 'updateSortOrder'])->name('mobileConfigSort');       
        Route::resource('mobileConfig', MobileMenuController::class);

        //Products
        Route::resource('productTypes', ProductTypeController::class);
        Route::resource('UOMS', UOMController::class);

        //Locations 
        Route::get('locationTypes/{location_type}', [LocationTypeController::class, 'showLocations'])->name('showLocations');
        Route::resource('locationTypes', LocationTypeController::class);

        //Zones 
        Route::resource('countZones', CountZoneController::class);
        Route::resource('pickZones', PickZoneController::class);
        Route::resource('storageZones', StorageZoneController::class);

        //Devices
        Route::resource('deviceTypes', DeviceTypeController::class);
        Route::resource('devices', DeviceController::class);

        //Printers
        Route::resource('printers', PrinterController::class);
        Route::resource('printerTypes', PrinterTypeController::class);

        //Outbound
        Route::resource('pickTypes', PickTypeController::class);

        //Inbound
        Route::resource('inboundConfig', InboundConfigController::class);
        Route::resource('storageRules', StorageRuleController::class);

        //Uploads
        Route::resource('configupload', ConfigUploadController::class);

        //Work
        Route::resource('workTypes', WorkTypeController::class);
    });
});

app/Http/Controllers/Configuration/Carriers/CarrierController.php
<?php

namespace App\Http\Controllers\Configuration\Carriers;

use App\Http\Controllers\Controller;

use App\Http\Requests\Carriers\StoreCarrierRequest;
use App\Http\Requests\Carriers\UpdateCarrierRequest;

use App\Models\Carriers\Carrier;

class CarrierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCarrierRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCarrierRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function show(Carrier $carrier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function edit(Carrier $carrier)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCarrierRequest  $request
     * @param  \App\Models\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCarrierRequest $request, Carrier $carrier)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Carrier $carrier)
    {
        //
    }
}

app/Http/Controllers/Configuration/Carriers/CarrierServiceLevelController.php
<?php

namespace App\Http\Controllers\Configuration\Carriers;

use App\Http\Controllers\Controller;

use App\Http\Requests\Carriers\StoreCarrierServiceLevelRequest;
use App\Http\Requests\Carriers\UpdateCarrierServiceLevelRequest;

use App\Models\Carriers\CarrierServiceLevel;


class CarrierServiceLevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCarrierServiceLevelRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCarrierServiceLevelRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Carriers\CarrierServiceLevel  $carrierServiceLevel
     * @return \Illuminate\Http\Response
     */
    public function show(CarrierServiceLevel $carrierServiceLevel)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Carriers\CarrierServiceLevel  $carrierServiceLevel
     * @return \Illuminate\Http\Response
     */
    public function edit(CarrierServiceLevel $carrierServiceLevel)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCarrierServiceLevelRequest  $request
     * @param  \App\Models\Carriers\CarrierServiceLevel  $carrierServiceLevel
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCarrierServiceLevelRequest $request, CarrierServiceLevel $carrierServiceLevel)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Carriers\CarrierServiceLevel  $carrierServiceLevel
     * @return \Illuminate\Http\Response
     */
    public function destroy(CarrierServiceLevel $carrierServiceLevel)
    {
        //
    }
}

app/Http/Controllers/Configuration/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Configuration\Dashboard;

use App\Http\Controllers\Controller;

use App\Models\Zones\CountZone;
use App\Models\Device;
use App\Models\Location;
use App\Models\LocationType;
use App\Models\Zones\PickZone;
use App\Models\Zones\StorageZone;
use App\Models\User;

class DashboardController extends Controller
{

    public function __invoke()
    {

        $users = User::count();
        $storageZones = StorageZone::count();
        $countZones = CountZone::count();
        $pickZones = PickZone::count();
        $locationTypes = LocationType::count();
        $locations = Location::count();
        $devices = Device::count();

        
        return view('configuration.dashboard', [
            'users' => $users,
            'storageZones' => $storageZones,
            'countZones' => $countZones,
            'pickZones' => $pickZones,
            'locationTypes' => $locationTypes,
            'locations' => $locations,
            'devices' => $devices,
        ]);

    }
}

app/Http/Controllers/Configuration/Devices/DeviceController.php
<?php

namespace App\Http\Controllers\Configuration\Devices;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateDeviceRequest;
use App\Models\Device;
use App\Models\DeviceType;
use App\Services\MobileDevices\MobileDeviceService;
use Illuminate\Contracts\View\View;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use InvalidArgumentException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;

class DeviceController extends Controller
{

    /** @return void  */
    public function __construct()
    {
        
        $this->deviceService = new MobileDeviceService;
    }


    /**
     * @return View|Factory 
     * @throws InvalidArgumentException 
     * @throws BindingResolutionException 
     */
    public function index()
    {
        return view('configuration.devices.devices', [
            'devices' => Device::with('deviceType')->paginate(20),
            'deviceTypes' => DeviceType::all()
        ]);
    }

    /**
     * @param CreateDeviceRequest $request 
     * @return RedirectResponse 
     * @throws RouteNotFoundException 
     */
    public function store(CreateDeviceRequest $request)
    {

        $this->deviceService->store($request->validated());

        return redirect()->route('config.devices.index');

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Configuration/Devices/DeviceTypeController.php
<?php

namespace App\Http\Controllers\Configuration\Devices;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateDeviceTypeRequest;
use App\Services\MobileDevices\DeviceTypeService;

class DeviceTypeController extends Controller
{

    private $deviceTypeService;

    public function __construct()
    {

        $this->deviceTypeService = new DeviceTypeService;
    }
    

    public function index()
    {

        return view('configuration.devices.device-types', [
            'deviceTypes' => $this->deviceTypeService->getDeviceTypesWithDeviceCount(),
        ]);
    }


    public function store(CreateDeviceTypeRequest $request)
    {

        $this->deviceTypeService->store($request->validated());

        return redirect()->route('config.deviceTypes.index');
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Configuration/Events/EventsController.php
<?php

namespace app\Http\Controllers\Events;

use App\Http\Controllers\Controller;
use App\Models\Events;
use Illuminate\Http\Request;


class EventsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function show(Events $events)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function edit(Events $events)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Events $events)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function destroy(Events $events)
    {
        //
    }
}

app/Http/Controllers/Configuration/MobileConfiguration/MobileMenuController.php
<?php

namespace App\Http\Controllers\Configuration\MobileConfiguration;

use App\Http\Controllers\Controller;
use App\Models\MobileMenu;
use App\Services\MobileMenu\MobileMenuService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MobileMenuController extends Controller
{

    private $mobileMenuService;

    public function __construct()
    {

        $this->mobileMenuService = new MobileMenuService;
    }


    public function index()
    {

        return view('MobileConfiguration.mobile-display-options', [
            'menus' => $this->mobileMenuService->getMainMenu()
        ]);
    }


    public function update(Request $request)
    {

        $menu = MobileMenu::select('id', 'visible')
            ->where('id', $request->mobileMenu)
            ->where('screen', $request->screen)
            ->first();

        $menu->visible ? $menu->toggleEnabled(0) : $menu->toggleEnabled(1);
    }


    public function updateSortOrder(Request $request)
    {

        $this->mobileMenuService->updateSortOrder($request);
    }
}

resources/views/configuration/config-upload.blade.php
<x-wms-layout>
    @section('content')
        <div class="flex-1">
            @include('configuration.navbar')
            @include('flash-message')
            <div class="bg-white w-1/4 p-2 ml-4 mt-2 rounded-lg border-2 border-gray-300">
                <h1 class="font-bold text-lg pb-2">{{ __('Upload Locations and Zones') }}</h1>
                <form action="{{ route('config.configupload.store') }}" method="POST" enctype="multipart/form-data">
                    <input type="file" name="location_upload" class="pb-4 focus:outline-none" required />
                    @error('file')
                        <div class="text-lg text-red-500 ml-1 pt-2">
                            {{ __('Please choose a file to upload.') }}
                        </div>
                    @enderror
                    <br />
                    <p class="text-sm font-bold">{{ __('Note:') }}</p>
                    <p class="text-sm pb-2">
                        {{ __('This will create storage locations, and if they
                                             don\'t exist already the following items will also be created:') }}
                    </p>
                    <p class="text-sm">&#8226; {{ __('Location Types') }}</p>
                    <p class="text-sm">&#8226; {{ __('Storage Zones') }}</p>
                    <p class="text-sm">&#8226; {{ __('Pick Zones') }}</p>
                    <p class="text-sm pb-2">&#8226; {{ __('Count Zones') }}</p>
                    <p class="text-sm italic mb-4">
                        {{ __('These Items will not be deleted if they\'re missing from the file but already exist with different names.') }}
                    </p>
                    <p class="text-sm italic mb-4 text-red-500">
                        {{ __('If Locations already exist they will be OVERWRITTEN with the content of this file.') }}
                    </p>
                    <p class="text-sm font-bold underline mb-2">
                        {{ __('Remember to check the Dashboard for config warnings after this upload!') }}</p>
                    <button type="submit"
                        class=" bg-yellow-300 hover:bg-yellow-600 p-2 rounded-lg shadow mb-2 focus:outline-none">{{ __('Upload
                                                Selected
                                                File') }}</button>

                    @csrf
                </form>
            </div>
        </div>
    @endsection
</x-wms-layout>

resources/views/configuration/constraints.blade.php
<x-wms-layout>
    @section('content')
    <div class="h-full w-full">
    @include('outbound.navbar')
    <div class="flex justify-between justify-items-center h-14 shadow-lg">
        <h1 class="flex font-semibold text-2xl px-4 items-center py-2">{{__('Constraints (TODO)') }}</h1>
    </div>
    <h1>constraints by customer
        <p>
            on/off <br />
            on/off by customer <br />
            on/off by product (add this to product settings) <br />
        </p>    
    </h1>
    @endsection
    </div>
</x-wms-layout>

resources/views/configuration/dashboard.blade.php
<x-wms-layout>
    @section('content')
    <div class="h-auto">
    @include('configuration.navbar')
           <div class="flex justify-between justify-items-center h-14 shadow-lg">
                <h1 class="flex font-semibold text-2xl px-4 items-center py-2">{{__('Configuration Dashboard') }}</h1>
            </div>
            <div class="grid grid-flow-col grid-cols-3 grid-rows-3 gap-2 pt-2 px-2">
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class=" font-bold text-xl bg-gray-300 text-center">{{ __('Users') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center ">{{ $users }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class=" font-bold text-xl bg-gray-300 text-center">{{ __('Storage Zones') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center ">{{ $storageZones }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class="font-bold text-xl bg-gray-300 text-center">{{ __('Pick Zones') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center ">{{ $pickZones }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class=" font-bold text-xl bg-gray-300 text-center">{{ __('Count Zones') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center ">{{ $countZones }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class=" font-bold text-xl bg-gray-300 text-center">{{ __('Location Types') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center ">{{ $locationTypes }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class="font-bold text-xl bg-gray-300 text-center">{{ __('Locations') }}</div>
                    <a href="{{ route('location.index') }}">
                       <div class="w-full pt-2 font-extrabold text-2xl text-center text-blue-500 hover:text-blue-800">{{ $locations }}</div>
                    </a>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class="px-8 pt-2 font-bold text-xl bg-gray-300 text-center">{{ __('Warnings') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center text-red-500 ">{{ __('10') }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class="px-8 pt-2 font-bold text-xl bg-gray-300 text-center">{{ __('Devices') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center">{{ $devices }}</div>
                </div>
                <div class="border-2 rounded-lg bg-gray-200">
                    <div class="px-8 pt-2 font-bold text-xl bg-gray-300 text-center">{{ __('Logged in Users') }}</div>
                    <div class="w-full pt-2 font-extrabold text-2xl text-center">{{ __('10') }}</div>
                </div>
            </div>
    </div>
    @endsection
</x-wms-layout>